### ISSUE TITLE
Bundling extension is missing

### ISSUE THREAD

**Issue by weedkiller** [mykeels/Extensions#1]
Hi, I ran in to a similar problem and wanted to use your bundling, [recommeneded here on SO](http://stackoverflow.com/questions/20248612/create-a-script-bundle-from-multiple-cdn-locations) , but the file is missing

https://github.com/mykeels/Extensions/tree/master/CdnBundle

is this in a different place?

thanks

**Comment by mykeels** [comment]
It's here now ... https://github.com/mykeels/CdnBundle

**Comment by weedkiller** [comment]
thanks, do you have the ASP MVC version before core.. the 4.5 version

**Comment by mykeels** [comment]
It's already in .NET framework 4.5 ... The .net core version isn't complete yet
